### ISSUE TITLE
Rebase to v1.10.18 versions of vdb geth

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-db-validator#6]
Child of https://github.com/vulcanize/go-ethereum/issues/231

- [x] v3 release that uses the new v1.10.18-statediff-3.2.1 release of vdb geth (off of https://github.com/vulcanize/ipld-eth-db-validator/tree/release-v3.0.0)
- [x] v4 release that uses the new v1.10.18-statediff-4.0.1-alpha release of vdb geth (off of https://github.com/vulcanize/ipld-eth-db-validator/tree/release-v4.0.0-alpha)

This may also involve updating the dependencies on ipfs-ethdb and ipld-eth-server to the versions resultant of https://github.com/vulcanize/ipfs-ethdb/issues/34 and https://github.com/vulcanize/ipld-eth-server/issues/158

**Comment by abdulrabbani00** [comment]
Final:

* v3 - https://github.com/vulcanize/ipld-eth-db-validator/releases/tag/v3.0.1
* v4 - Coming soon

**Comment by abdulrabbani00** [comment]
@ashwinphatak -  I see that you and your team have been actively contributing to this repo in the last few hours. Should I wait to cut the v4 release? Steps I plan on taking when it is time to cut the release. 

1. Branch off of sharding --> feature/update-go-geth-sharding
2. git merge main into feature/update-go-geth-sharding
3. Handle any conflicts.
4. Create a PR: feature/update-go-geth-sharding --> sharding
5. Create a tagged release.

**Comment by prathamesh0** [comment]
@abdulrabbani00 We are done with the changes to main for now. The steps you mentioned for merging the changes into sharding sound good. You can refer to https://github.com/vulcanize/ipld-eth-db-validator/pull/11 while resolving conflicts.
